Demoing how to checkin code for a feature branch
Swen670Grp1/cytoscape-platform-tests-js pull request #1
Opened 2018-10-23 01:51 UTC by kemaric

Demoing a pull request to the team.

2018-10-23 01:54 UTC, kouissar reviewed
please add actual details instead of TBD

2018-10-23 01:55 UTC, kouissar approved these changes
you're good now!

2018-10-23 01:55 UTC, OliviaSims21 requested changes
please make change to TBD

2018-10-24 21:49 UTC, swen670group1 commented
Test adding comments

2018-10-30 02:15 UTC, closed without merging