Feature/slide design
Swen670Grp1/cytoscape-platform-tests-js pull request #4
Opened 2018-10-30 02:10 UTC by kemaric

This is the base implementation of the Slide and Test Session Model data. Feel free to suggest any changes or make comments.

2018-10-30 02:38 UTC, kemaric commented on js/slidesModel.js
> +        this.answer = "";
Change this to be `expectedAnswer` because this is confusing with `userReponse`.

2018-10-30 02:43 UTC, kemaric commented on js/slidesModel.js
> +        this._label = label;
Label can be an object that has a category, and an optional ordering. ie {category: "Diffususion", order:1}.

2018-10-31 03:35 UTC, kouissar requested changes
Looks good to me. Please integrate the functionality so we could test and provide feedback based on the tested app.

2018-11-06 03:49 UTC, kouissar approved these changes

2018-11-06 04:40 UTC, OliviaSims21 commented on js/slides/slidesModel.js
> +        this.options = [];
This may not need to be necessary. However, keep for now incase it becomes useful when we start to insert tests.

2018-11-07 05:06 UTC, kouissar approved these changes
approved

2018-11-07 05:06 UTC, kouissar approved these changes

2018-11-07 05:07 UTC, kouissar approved these changes

2018-11-07 05:08 UTC, kouissar approved these changes
Approved

2018-11-09 02:20 UTC, skatulich approved these changes
Don't see any issues.

2018-11-09 03:01 UTC, merged