Feature/disable controls
Swen670Grp1/cytoscape-platform-tests-js pull request #49
Opened 2018-11-27 21:48 UTC by OliviaSims21

This is for when the error pops up the arrow controls are disabled.

2018-11-28 00:36 UTC, rpaudyal4769 submitted a review, later dismissed

2018-11-28 05:59 UTC, kouissar commented
This looking good. There was one case I detected where controls weren't hidden, see picture ( I believe this is related to the spot for catch all errors (window.onerror) in particular updateError() function. If you address this last piece, this should be good to go.

![screen shot 2018-11-28 at 12 49 39 am](https://user-images.githubusercontent.com/8869957/49131963-3dcbe400-f2a8-11e8-86c1-4f869b5da501.png)

2018-11-28 06:00 UTC, kouissar requested changes
Olivia, pls see my comment above.

2018-11-29 18:46 UTC, OliviaSims21 commented
Made the change Rafik. Please approve.

2018-11-30 04:47 UTC, kouissar approved these changes

2018-11-30 04:48 UTC, kemaric approved these changes

2018-11-30 04:48 UTC, merged